#!/usr/bin/env node
// Generates registry/data.js from the conformance corpus + the adapter table — the single
// source of truth, so the registry page can never drift from what the repo actually ships.
//   node registry/build.mjs           # (re)write registry/data.js
//   node registry/build.mjs --check   # exit 1 if registry/data.js is stale (CI/test guard)
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const repo = join(here, "..");
const manifest = JSON.parse(readFileSync(join(repo, "conformance/manifest.json"), "utf8"));

// The four v1 adapters. status/native are the honest claims from docs/harness-emit-analysis.md.
const ADAPTERS = [
  { name: "claude-code", label: "Claude Code", status: "verified", native: "tool_use / tool_result, toolu_* ids", source: "packages/capture/src/from-claude-code.ts" },
  { name: "codex-cli", label: "Codex CLI", status: "verified", native: "function_call / function_call_output, call_id", source: "packages/capture/src/from-codex.ts" },
  { name: "gemini-cli", label: "Gemini CLI", status: "verified", native: "typed log items, run_shell_command", source: "packages/capture/src/from-gemini.ts" },
  { name: "langgraph", label: "LangGraph / LangSmith", status: "provisional", native: "run tree (run_type); 3 export shapes", source: "packages/capture/src/from-langgraph.ts" },
];

const cases = manifest.cases.map((c) => {
  const doc = JSON.parse(readFileSync(join(repo, "conformance", c.file), "utf8"));
  return {
    file: c.file,
    demonstrates: c.demonstrates,
    must: c.must,
    harness: doc.harness?.name ?? null,
    steps: Array.isArray(doc.steps) ? doc.steps.length : 0,
    status: doc.outcome?.status ?? null,
    verdict: doc.outcome?.verdict?.diagnosis ?? null,
    json: JSON.stringify(doc, null, 2),
  };
});

const data = {
  ot_version: manifest.ot_version,
  adapters: ADAPTERS,
  cases,
};
const out =
  "// GENERATED by registry/build.mjs — do not edit by hand. Run: node registry/build.mjs\n" +
  "window.__REGISTRY__ = " + JSON.stringify(data, null, 2) + ";\n";

const target = join(here, "data.js");
if (process.argv.includes("--check")) {
  let cur = "";
  try { cur = readFileSync(target, "utf8"); } catch { /* missing -> stale */ }
  if (cur !== out) { console.error("registry/data.js is STALE — run: node registry/build.mjs"); process.exit(1); }
  console.log("registry/data.js is current"); process.exit(0);
}
writeFileSync(target, out);
console.log(`registry/data.js written — ${cases.length} cases, ${ADAPTERS.length} adapters`);
